name: opencv46
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aom=3.9.1
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.16.2
  - double-conversion=3.3.1
  - ffmpeg=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.4
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=12.2.0
  - hdf5=1.14.6
  - icu=75.1
  - imath=3.2.1
  - jasper=4.2.8
  - krb5=1.21.3
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libasprintf=0.25.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libcblas=3.11.0
  - libclang-cpp19.1=19.1.7
  - libclang13=21.1.8
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgettextpo=0.25.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.2
  - libhwloc=2.12.2
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - libllvm19=19.1.7
  - libllvm21=21.1.8
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopencv=4.12.0
  - libopenvino=2025.2.0
  - libopenvino-arm-cpu-plugin=2025.2.0
  - libopenvino-auto-batch-plugin=2025.2.0
  - libopenvino-auto-plugin=2025.2.0
  - libopenvino-hetero-plugin=2025.2.0
  - libopenvino-ir-frontend=2025.2.0
  - libopenvino-onnx-frontend=2025.2.0
  - libopenvino-paddle-frontend=2025.2.0
  - libopenvino-pytorch-frontend=2025.2.0
  - libopenvino-tensorflow-frontend=2025.2.0
  - libopenvino-tensorflow-lite-frontend=2025.2.0
  - libopus=1.6
  - libpng=1.6.53
  - libpq=18.1
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libvulkan-loader=1.4.328.1
  - libwebp-base=1.6.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - ncurses=6.5
  - numpy=1.26.4
  - opencv=4.12.0
  - openexr=3.3.5
  - openh264=2.6.0
  - openldap=2.6.10
  - openssl=3.6.0
  - pango=1.56.4
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - pugixml=1.15
  - py-opencv=4.12.0
  - python=3.9.23
  - python_abi=3.9
  - qt6-main=6.9.3
  - rav1e=0.7.1
  - readline=8.3
  - scipy=1.13.1
  - sdl2=2.32.56
  - sdl3=3.2.30
  - setuptools=80.9.0
  - snappy=1.2.2
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - zstd=1.5.7
prefix: /Users/holy/anaconda3/envs/opencv46
